server:
  port: 8888
spring:
  application:
    name: springcicddemo1

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/edudb}
    username: ${SPRING_DATASOURCE_USERNAME:jdbctest}
    password: ${SPRING_DATASOURCE_PASSWORD:jdbctest}
    driver-class-name: com.mysql.cj.jdbc.Driver

  docker:
    compose:
      skip:
        in-tests: false
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql

logging:
  level:
    org.hibernate: info
